# Site settings
title: Peter's General Store
email: hhww.gao@gmail.com
description: > # this means to ignore newlines until "url:"
  I am a programmer and maker.
url: "http://hwgao.github.io" # the base hostname & protocol for your site
twitter_username: hwgao
github_username:  hwgao

# Build settings
markdown: kramdown
